FROM jenkins/jenkins:lts

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# add the admin user
# COPY /config/users "$JENKINS_HOME"/users/

# Add the main config file to the jenkins path
# COPY /config/jenkins_home_config.xml "$JENKINS_HOME"/config.xml

# Name the jobs
ARG job_name_1="seed-job"

# Create the job workspaces
RUN mkdir -p "$JENKINS_HOME"/workspace/${job_name_1}

# Create the jobs folder recursively
RUN mkdir -p "$JENKINS_HOME"/jobs/${job_name_1}

# Add the custom configs to the container
COPY /config/${job_name_1}_config.xml "$JENKINS_HOME"/jobs/${job_name_1}/config.xml

# Create build file structure
RUN mkdir -p "$JENKINS_HOME"/jobs/${job_name_1}/latest/
RUN mkdir -p "$JENKINS_HOME"/jobs/${job_name_1}/builds/1/

USER jenkins