FROM jenkins/jenkins:lts

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# add the admin user
# COPY /configs/users "$JENKINS_HOME"/users/

# Add the main config file to the jenkins path
# COPY /configs/jenkins_home_config.xml "$JENKINS_HOME"/config.xml

# Name the jobs
ARG job-1="seed-job"

# Create the job workspaces
RUN mkdir -p "$JENKINS_HOME"/workspace/${job-1}

# Create the jobs folder recursively
RUN mkdir -p "$JENKINS_HOME"/jobs/${job-1}

# Add the custom configs to the container
COPY /configs/${job-1}-config.xml "$JENKINS_HOME"/jobs/${job-1}/config.xml

# Create build file structure
#RUN mkdir -p "$JENKINS_HOME"/jobs/${job-1}/latest/

USER jenkins