# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: jenkins

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-jnlp
# spec:
#   type: ClusterIP
#   ports:
#     - port: 50000
#       targetPort: 50000
#   selector:
#     app: jenkins

apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins-master
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: jenkins-master