# ClusterIP: Stable internal cluster IP
# LoadBalancer: Integrates NodePort with cloud-based load balancers
# NodePort: exposes the app outside of the cluster by adding a cluster-wide port on top of Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: default
spec:
  type: NodePort # exposes the app outside of the cluster by adding a cluster-wide port on top of Cluster IP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: slave
  selector:
    rub: jenkins-svc