# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: jenkins

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-jnlp
# spec:
#   type: ClusterIP
#   ports:
#     - port: 50000
#       targetPort: 50000
#   selector:
#     app: jenkins

# ClusterIP: Stable internal cluster IP
# LoadBalancer: Integrates NodePort with cloud-based load balancers
# NodePort: exposes the app outside of the cluster by adding a cluster-wide port on top of Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins
spec:
  type: NodePort # exposes the app outside of the cluster by adding a cluster-wide port on top of Cluster IP
  ports:
    - port: 8080
      nodePort: 30000
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: slave
  selector:
    app: jenkins