---
- name: Jenkins master installation
  hosts: all # value here is important!
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: EX
      shell: kubectl create -f jenkins-deployment.yaml

    - name: EX
      shell: kubectl create -f jenkins-service.yaml

    - name: EX
      shell: kubectl describe pods

    - name: EX
      shell: kubectl cluster-info

    - name: EX
      shell: kubectl get service

    - name: EX
      shell: kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts:default

